# Generated by Django 4.0.1 on 2022-06-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account_delete_feed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='MyUser',
        ),
    ]
