# Generated by Django 4.0.1 on 2022-06-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_myuser_address_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='email'),
        ),
    ]
